######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 25 19:11:41 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h ../webparse/web.h ../webparse/set.h
SOURCES += mainWindow.cpp mainWinex.cpp ../webparse/webImpl.cpp
